version: 0.2
phases:
  install:
    runtime-version:
      dotnet: latest
  pre_build:
    commands:
      - echo Build dotnet application
      - dotnet publish -c Release
      - echo Get ecr login credentials...
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 460234074473.dkr.ecr.eu-west-1.amazonaws.com
      - aws codeartifact login --tool dotnet --repository helpmycase-backend --domain helpmycase-backend --domain-owner 460234074473
      - dotnet nuget add source "https://helpmycase-backend-460234074473.d.codeartifact.eu-west-1.amazonaws.com/nuget/helpmycase-backend/v3/index.json" -n "helpmycase-backend/helpmycase-backend"
  build:
    commands:
      - echo build docker image --source helpmycase-backend/helpmycase-backend
      - docker build -t handlemycaseclientregistry-clientbackendf728ad9b-irvzrprmeerk .
      - docker tag handlemycaseclientregistry-clientbackendf728ad9b-irvzrprmeerk:latest 460234074473.dkr.ecr.eu-west-1.amazonaws.com/handlemycaseclientregistry-clientbackendf728ad9b-irvzrprmeerk:latest
  post_build:
    commands:
      - echo Push docker to ecr registry
      - docker push 460234074473.dkr.ecr.eu-west-1.amazonaws.com/handlemycaseclientregistry-clientbackendf728ad9b-irvzrprmeerk:latest
      