  # syntax=docker/dockerfile:1
  #FROM mcr.microsoft.com/dotnet/aspnet:5.0.17-buster-slim-arm64v8
  FROM mcr.microsoft.com/dotnet/aspnet:5.0
  COPY bin/Debug/net5.0/publish/ ./app
  ENV ASPNETCORE_URLS http://+:8080
  ENV ASPNETCORE_ENVIRONMENT Development
  WORKDIR "/app"
  EXPOSE 8080
  ENTRYPOINT ["dotnet", "./client.dll"]